[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

